use super::AddressingMode;

pub type Instruction = Option<(AddressingMode, Nmeonic)>;

#[derive(Clone, Copy)]
pub enum Nmeonic {
    None,
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
}

pub const LOOKUP: [Instruction; 256] = [
    Some((AddressingMode::Implied, Nmeonic::BRK)),
    Some((AddressingMode::IndirectX, Nmeonic::ORA)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage, Nmeonic::ORA)),
    Some((AddressingMode::ZeroPage, Nmeonic::ASL)),
    None,
    Some((AddressingMode::Implied, Nmeonic::PHP)),
    Some((AddressingMode::Immediate, Nmeonic::ORA)),
    Some((AddressingMode::Accumulator, Nmeonic::ASL)),
    None,
    None,
    Some((AddressingMode::Absolute, Nmeonic::ORA)),
    Some((AddressingMode::Absolute, Nmeonic::ASL)),
    None,
    Some((AddressingMode::Relative, Nmeonic::BPL)),
    Some((AddressingMode::IndirectY, Nmeonic::ORA)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Nmeonic::ORA)),
    Some((AddressingMode::ZeroPageX, Nmeonic::ASL)),
    None,
    Some((AddressingMode::Implied, Nmeonic::CLC)),
    Some((AddressingMode::AbsoluteY, Nmeonic::ORA)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Nmeonic::ORA)),
    Some((AddressingMode::AbsoluteX, Nmeonic::ASL)),
    None,
    Some((AddressingMode::Absolute, Nmeonic::JSR)),
    Some((AddressingMode::IndirectX, Nmeonic::AND)),
    None,
    None,
    Some((AddressingMode::ZeroPage, Nmeonic::BIT)),
    Some((AddressingMode::ZeroPage, Nmeonic::AND)),
    Some((AddressingMode::ZeroPage, Nmeonic::ROL)),
    None,
    Some((AddressingMode::Implied, Nmeonic::PLP)),
    Some((AddressingMode::Immediate, Nmeonic::AND)),
    Some((AddressingMode::Accumulator, Nmeonic::ROL)),
    None,
    Some((AddressingMode::Absolute, Nmeonic::BIT)),
    Some((AddressingMode::Absolute, Nmeonic::AND)),
    Some((AddressingMode::Absolute, Nmeonic::ROL)),
    None,
    Some((AddressingMode::Relative, Nmeonic::BMI)),
    Some((AddressingMode::IndirectY, Nmeonic::AND)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Nmeonic::AND)),
    Some((AddressingMode::ZeroPageX, Nmeonic::ROL)),
    None,
    Some((AddressingMode::Implied, Nmeonic::SEC)),
    Some((AddressingMode::AbsoluteY, Nmeonic::AND)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Nmeonic::AND)),
    Some((AddressingMode::AbsoluteX, Nmeonic::ROL)),
    None,
    Some((AddressingMode::Implied, Nmeonic::RTI)),
    Some((AddressingMode::IndirectX, Nmeonic::EOR)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage, Nmeonic::EOR)),
    Some((AddressingMode::ZeroPage, Nmeonic::LSR)),
    None,
    Some((AddressingMode::Implied, Nmeonic::PHA)),
    Some((AddressingMode::Immediate, Nmeonic::EOR)),
    Some((AddressingMode::Accumulator, Nmeonic::LSR)),
    None,
    Some((AddressingMode::Absolute, Nmeonic::JMP)),
    Some((AddressingMode::Absolute, Nmeonic::EOR)),
    Some((AddressingMode::Absolute, Nmeonic::LSR)),
    None,
    Some((AddressingMode::Relative, Nmeonic::BVC)),
    Some((AddressingMode::IndirectY, Nmeonic::EOR)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Nmeonic::EOR)),
    Some((AddressingMode::ZeroPageX, Nmeonic::LSR)),
    None,
    Some((AddressingMode::Implied, Nmeonic::CLI)),
    Some((AddressingMode::AbsoluteY, Nmeonic::EOR)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Nmeonic::EOR)),
    Some((AddressingMode::AbsoluteX, Nmeonic::LSR)),
    None,
    Some((AddressingMode::Implied, Nmeonic::RTS)),
    Some((AddressingMode::IndirectX, Nmeonic::ADC)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage, Nmeonic::ADC)),
    Some((AddressingMode::ZeroPage, Nmeonic::ROR)),
    None,
    Some((AddressingMode::Implied, Nmeonic::PLA)),
    Some((AddressingMode::Immediate, Nmeonic::ADC)),
    Some((AddressingMode::Accumulator, Nmeonic::ROR)),
    None,
    Some((AddressingMode::Indirect, Nmeonic::JMP)),
    Some((AddressingMode::Absolute, Nmeonic::ADC)),
    Some((AddressingMode::Absolute, Nmeonic::ROR)),
    None,
    Some((AddressingMode::Relative, Nmeonic::BVS)),
    Some((AddressingMode::IndirectY, Nmeonic::ADC)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Nmeonic::ADC)),
    Some((AddressingMode::ZeroPageX, Nmeonic::ROR)),
    None,
    Some((AddressingMode::Implied, Nmeonic::SEI)),
    Some((AddressingMode::AbsoluteY, Nmeonic::ADC)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Nmeonic::ADC)),
    Some((AddressingMode::AbsoluteX, Nmeonic::ROR)),
    None,
    None,
    Some((AddressingMode::IndirectX, Nmeonic::STA)),
    None,
    None,
    Some((AddressingMode::ZeroPage, Nmeonic::STY)),
    Some((AddressingMode::ZeroPage, Nmeonic::STA)),
    Some((AddressingMode::ZeroPage, Nmeonic::STX)),
    None,
    Some((AddressingMode::Implied, Nmeonic::DEY)),
    None,
    Some((AddressingMode::Implied, Nmeonic::TXA)),
    None,
    Some((AddressingMode::Absolute, Nmeonic::STY)),
    Some((AddressingMode::Absolute, Nmeonic::STA)),
    Some((AddressingMode::Absolute, Nmeonic::STX)),
    None,
    Some((AddressingMode::Relative, Nmeonic::BCC)),
    Some((AddressingMode::IndirectY, Nmeonic::STA)),
    None,
    None,
    Some((AddressingMode::ZeroPageX, Nmeonic::STY)),
    Some((AddressingMode::ZeroPageX, Nmeonic::STA)),
    Some((AddressingMode::ZeroPageY, Nmeonic::STX)),
    None,
    Some((AddressingMode::Implied, Nmeonic::TYA)),
    Some((AddressingMode::AbsoluteY, Nmeonic::STA)),
    Some((AddressingMode::Implied, Nmeonic::TXS)),
    None,
    None,
    Some((AddressingMode::AbsoluteX, Nmeonic::STA)),
    None,
    None,
    Some((AddressingMode::Immediate, Nmeonic::LDY)),
    Some((AddressingMode::IndirectX, Nmeonic::LDA)),
    Some((AddressingMode::Immediate, Nmeonic::LDX)),
    None,
    Some((AddressingMode::ZeroPage, Nmeonic::LDY)),
    Some((AddressingMode::ZeroPage, Nmeonic::LDA)),
    Some((AddressingMode::ZeroPage, Nmeonic::LDX)),
    None,
    Some((AddressingMode::Implied, Nmeonic::TAY)),
    Some((AddressingMode::Immediate, Nmeonic::LDA)),
    Some((AddressingMode::Implied, Nmeonic::TAX)),
    None,
    Some((AddressingMode::Absolute, Nmeonic::LDY)),
    Some((AddressingMode::Absolute, Nmeonic::LDA)),
    Some((AddressingMode::Absolute, Nmeonic::LDX)),
    None,
    Some((AddressingMode::Relative, Nmeonic::BCS)),
    Some((AddressingMode::IndirectY, Nmeonic::LDA)),
    None,
    None,
    Some((AddressingMode::ZeroPageX, Nmeonic::LDY)),
    Some((AddressingMode::ZeroPageX, Nmeonic::LDA)),
    Some((AddressingMode::ZeroPageY, Nmeonic::LDX)),
    None,
    Some((AddressingMode::Implied, Nmeonic::CLV)),
    Some((AddressingMode::AbsoluteY, Nmeonic::LDA)),
    Some((AddressingMode::Implied, Nmeonic::TSX)),
    None,
    Some((AddressingMode::AbsoluteX, Nmeonic::LDY)),
    Some((AddressingMode::AbsoluteX, Nmeonic::LDA)),
    Some((AddressingMode::AbsoluteY, Nmeonic::LDX)),
    None,
    Some((AddressingMode::Immediate, Nmeonic::CPY)),
    Some((AddressingMode::IndirectX, Nmeonic::CMP)),
    None,
    None,
    Some((AddressingMode::ZeroPage, Nmeonic::CPY)),
    Some((AddressingMode::ZeroPage, Nmeonic::CMP)),
    Some((AddressingMode::ZeroPage, Nmeonic::DEC)),
    None,
    Some((AddressingMode::Implied, Nmeonic::INY)),
    Some((AddressingMode::Immediate, Nmeonic::CMP)),
    Some((AddressingMode::Implied, Nmeonic::DEX)),
    None,
    Some((AddressingMode::Absolute, Nmeonic::CPY)),
    Some((AddressingMode::Absolute, Nmeonic::CMP)),
    Some((AddressingMode::Absolute, Nmeonic::DEC)),
    None,
    Some((AddressingMode::Relative, Nmeonic::BNE)),
    Some((AddressingMode::IndirectY, Nmeonic::CMP)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Nmeonic::CMP)),
    Some((AddressingMode::ZeroPageX, Nmeonic::DEC)),
    None,
    Some((AddressingMode::Implied, Nmeonic::CLD)),
    Some((AddressingMode::AbsoluteY, Nmeonic::CMP)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Nmeonic::CMP)),
    Some((AddressingMode::AbsoluteX, Nmeonic::DEC)),
    None,
    Some((AddressingMode::Immediate, Nmeonic::CPX)),
    Some((AddressingMode::IndirectX, Nmeonic::SBC)),
    None,
    None,
    Some((AddressingMode::ZeroPage, Nmeonic::CPX)),
    Some((AddressingMode::ZeroPage, Nmeonic::SBC)),
    Some((AddressingMode::ZeroPage, Nmeonic::INC)),
    None,
    Some((AddressingMode::Implied, Nmeonic::INX)),
    Some((AddressingMode::Immediate, Nmeonic::SBC)),
    Some((AddressingMode::Implied, Nmeonic::NOP)),
    None,
    Some((AddressingMode::Absolute, Nmeonic::CPX)),
    Some((AddressingMode::Absolute, Nmeonic::SBC)),
    Some((AddressingMode::Absolute, Nmeonic::INC)),
    None,
    Some((AddressingMode::Relative, Nmeonic::BEQ)),
    Some((AddressingMode::IndirectY, Nmeonic::SBC)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Nmeonic::SBC)),
    Some((AddressingMode::ZeroPageX, Nmeonic::INC)),
    None,
    Some((AddressingMode::Implied, Nmeonic::SED)),
    Some((AddressingMode::AbsoluteY, Nmeonic::SBC)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Nmeonic::SBC)),
    Some((AddressingMode::AbsoluteX, Nmeonic::INC)),
    None,
];
