use crate::cpu::{AddressingMode, Cpu, Instruction};

pub const LOOKUP: [Instruction; 256] = [
    Some((AddressingMode::Implied, Cpu::brk)),
    Some((AddressingMode::IndirectX, Cpu::ora)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage, Cpu::ora)),
    Some((AddressingMode::ZeroPage, Cpu::asl)),
    None,
    Some((AddressingMode::Implied, Cpu::php)),
    Some((AddressingMode::Immediate, Cpu::ora)),
    Some((AddressingMode::Accumulator, Cpu::asl)),
    None,
    None,
    Some((AddressingMode::Absolute, Cpu::ora)),
    Some((AddressingMode::Absolute, Cpu::asl)),
    None,
    Some((AddressingMode::Relative, Cpu::bpl)),
    Some((AddressingMode::IndirectY, Cpu::ora)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Cpu::ora)),
    Some((AddressingMode::ZeroPageX, Cpu::asl)),
    None,
    Some((AddressingMode::Implied, Cpu::clc)),
    Some((AddressingMode::AbsoluteY, Cpu::ora)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Cpu::ora)),
    Some((AddressingMode::AbsoluteX, Cpu::asl)),
    None,
    Some((AddressingMode::Absolute, Cpu::jsr)),
    Some((AddressingMode::IndirectX, Cpu::and)),
    None,
    None,
    Some((AddressingMode::ZeroPage, Cpu::bit)),
    Some((AddressingMode::ZeroPage, Cpu::and)),
    Some((AddressingMode::ZeroPage, Cpu::rol)),
    None,
    Some((AddressingMode::Implied, Cpu::plp)),
    Some((AddressingMode::Immediate, Cpu::and)),
    Some((AddressingMode::Accumulator, Cpu::rol)),
    None,
    Some((AddressingMode::Absolute, Cpu::bit)),
    Some((AddressingMode::Absolute, Cpu::and)),
    Some((AddressingMode::Absolute, Cpu::rol)),
    None,
    Some((AddressingMode::Relative, Cpu::bmi)),
    Some((AddressingMode::IndirectY, Cpu::and)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Cpu::and)),
    Some((AddressingMode::ZeroPageX, Cpu::rol)),
    None,
    Some((AddressingMode::Implied, Cpu::sec)),
    Some((AddressingMode::AbsoluteY, Cpu::and)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Cpu::and)),
    Some((AddressingMode::AbsoluteX, Cpu::rol)),
    None,
    Some((AddressingMode::Implied, Cpu::rti)),
    Some((AddressingMode::IndirectX, Cpu::eor)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage, Cpu::eor)),
    Some((AddressingMode::ZeroPage, Cpu::lsr)),
    None,
    Some((AddressingMode::Implied, Cpu::pha)),
    Some((AddressingMode::Immediate, Cpu::eor)),
    Some((AddressingMode::Accumulator, Cpu::lsr)),
    None,
    Some((AddressingMode::Absolute, Cpu::jmp)),
    Some((AddressingMode::Absolute, Cpu::eor)),
    Some((AddressingMode::Absolute, Cpu::lsr)),
    None,
    Some((AddressingMode::Relative, Cpu::bvc)),
    Some((AddressingMode::IndirectY, Cpu::eor)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Cpu::eor)),
    Some((AddressingMode::ZeroPageX, Cpu::lsr)),
    None,
    Some((AddressingMode::Implied, Cpu::cli)),
    Some((AddressingMode::AbsoluteY, Cpu::eor)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Cpu::eor)),
    Some((AddressingMode::AbsoluteX, Cpu::lsr)),
    None,
    Some((AddressingMode::Implied, Cpu::rts)),
    Some((AddressingMode::IndirectX, Cpu::adc)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage, Cpu::adc)),
    Some((AddressingMode::ZeroPage, Cpu::ror)),
    None,
    Some((AddressingMode::Implied, Cpu::pla)),
    Some((AddressingMode::Immediate, Cpu::adc)),
    Some((AddressingMode::Accumulator, Cpu::ror)),
    None,
    Some((AddressingMode::Indirect, Cpu::jmp)),
    Some((AddressingMode::Absolute, Cpu::adc)),
    Some((AddressingMode::Absolute, Cpu::ror)),
    None,
    Some((AddressingMode::Relative, Cpu::bvs)),
    Some((AddressingMode::IndirectY, Cpu::adc)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Cpu::adc)),
    Some((AddressingMode::ZeroPageX, Cpu::ror)),
    None,
    Some((AddressingMode::Implied, Cpu::sei)),
    Some((AddressingMode::AbsoluteY, Cpu::adc)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Cpu::adc)),
    Some((AddressingMode::AbsoluteX, Cpu::ror)),
    None,
    None,
    Some((AddressingMode::IndirectX, Cpu::sta)),
    None,
    None,
    Some((AddressingMode::ZeroPage, Cpu::sty)),
    Some((AddressingMode::ZeroPage, Cpu::sta)),
    Some((AddressingMode::ZeroPage, Cpu::stx)),
    None,
    Some((AddressingMode::Implied, Cpu::dey)),
    None,
    Some((AddressingMode::Implied, Cpu::txa)),
    None,
    Some((AddressingMode::Absolute, Cpu::sty)),
    Some((AddressingMode::Absolute, Cpu::sta)),
    Some((AddressingMode::Absolute, Cpu::stx)),
    None,
    Some((AddressingMode::Relative, Cpu::bcc)),
    Some((AddressingMode::IndirectY, Cpu::sta)),
    None,
    None,
    Some((AddressingMode::ZeroPageX, Cpu::sty)),
    Some((AddressingMode::ZeroPageX, Cpu::sta)),
    Some((AddressingMode::ZeroPageY, Cpu::stx)),
    None,
    Some((AddressingMode::Implied, Cpu::tya)),
    Some((AddressingMode::AbsoluteY, Cpu::sta)),
    Some((AddressingMode::Implied, Cpu::txs)),
    None,
    None,
    Some((AddressingMode::AbsoluteX, Cpu::sta)),
    None,
    None,
    Some((AddressingMode::Immediate, Cpu::ldy)),
    Some((AddressingMode::IndirectX, Cpu::lda)),
    Some((AddressingMode::Immediate, Cpu::ldx)),
    None,
    Some((AddressingMode::ZeroPage, Cpu::ldy)),
    Some((AddressingMode::ZeroPage, Cpu::lda)),
    Some((AddressingMode::ZeroPage, Cpu::ldx)),
    None,
    Some((AddressingMode::Implied, Cpu::tay)),
    Some((AddressingMode::Immediate, Cpu::lda)),
    Some((AddressingMode::Implied, Cpu::tax)),
    None,
    Some((AddressingMode::Absolute, Cpu::ldy)),
    Some((AddressingMode::Absolute, Cpu::lda)),
    Some((AddressingMode::Absolute, Cpu::ldx)),
    None,
    Some((AddressingMode::Relative, Cpu::bcs)),
    Some((AddressingMode::IndirectY, Cpu::lda)),
    None,
    None,
    Some((AddressingMode::ZeroPageX, Cpu::ldy)),
    Some((AddressingMode::ZeroPageX, Cpu::lda)),
    Some((AddressingMode::ZeroPageY, Cpu::ldx)),
    None,
    Some((AddressingMode::Implied, Cpu::clv)),
    Some((AddressingMode::AbsoluteY, Cpu::lda)),
    Some((AddressingMode::Implied, Cpu::tsx)),
    None,
    Some((AddressingMode::AbsoluteX, Cpu::ldy)),
    Some((AddressingMode::AbsoluteX, Cpu::lda)),
    Some((AddressingMode::AbsoluteY, Cpu::ldx)),
    None,
    Some((AddressingMode::Immediate, Cpu::cpy)),
    Some((AddressingMode::IndirectX, Cpu::cmp)),
    None,
    None,
    Some((AddressingMode::ZeroPage, Cpu::cpy)),
    Some((AddressingMode::ZeroPage, Cpu::cmp)),
    Some((AddressingMode::ZeroPage, Cpu::dec)),
    None,
    Some((AddressingMode::Implied, Cpu::iny)),
    Some((AddressingMode::Immediate, Cpu::cmp)),
    Some((AddressingMode::Implied, Cpu::dex)),
    None,
    Some((AddressingMode::Absolute, Cpu::cpy)),
    Some((AddressingMode::Absolute, Cpu::cmp)),
    Some((AddressingMode::Absolute, Cpu::dec)),
    None,
    Some((AddressingMode::Relative, Cpu::bne)),
    Some((AddressingMode::IndirectY, Cpu::cmp)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Cpu::cmp)),
    Some((AddressingMode::ZeroPageX, Cpu::dec)),
    None,
    Some((AddressingMode::Implied, Cpu::cld)),
    Some((AddressingMode::AbsoluteY, Cpu::cmp)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Cpu::cmp)),
    Some((AddressingMode::AbsoluteX, Cpu::dec)),
    None,
    Some((AddressingMode::Immediate, Cpu::cpx)),
    Some((AddressingMode::IndirectX, Cpu::sbc)),
    None,
    None,
    Some((AddressingMode::ZeroPage, Cpu::cpx)),
    Some((AddressingMode::ZeroPage, Cpu::sbc)),
    Some((AddressingMode::ZeroPage, Cpu::inc)),
    None,
    Some((AddressingMode::Implied, Cpu::inx)),
    Some((AddressingMode::Immediate, Cpu::sbc)),
    Some((AddressingMode::Implied, Cpu::nop)),
    None,
    Some((AddressingMode::Absolute, Cpu::cpx)),
    Some((AddressingMode::Absolute, Cpu::sbc)),
    Some((AddressingMode::Absolute, Cpu::inc)),
    None,
    Some((AddressingMode::Relative, Cpu::beq)),
    Some((AddressingMode::IndirectY, Cpu::sbc)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPageX, Cpu::sbc)),
    Some((AddressingMode::ZeroPageX, Cpu::inc)),
    None,
    Some((AddressingMode::Implied, Cpu::sed)),
    Some((AddressingMode::AbsoluteY, Cpu::sbc)),
    None,
    None,
    None,
    Some((AddressingMode::AbsoluteX, Cpu::sbc)),
    Some((AddressingMode::AbsoluteX, Cpu::inc)),
    None,
];
