pub type Instruction = Option<(AddressingMode, Mnemonic)>;

#[derive(Copy, Clone)]
pub enum AddressingMode {
    None,
    Accumulator,
    Relative,
    Implied,
    Indirect(IndexReg),
    Immediate,
    ZeroPage(IndexReg),
    Absolute(IndexReg),
}

#[derive(Clone, Copy, PartialEq)]
pub enum IndexReg {
    None,
    X,
    Y,
}

#[derive(Clone, Copy, Debug)]
pub enum Mnemonic {
    None,
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
}

pub const LOOKUP: [Instruction; 256] = [
    Some((AddressingMode::Implied, Mnemonic::BRK)),
    Some((AddressingMode::Indirect(IndexReg::X), Mnemonic::ORA)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::ORA)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::ASL)),
    None,
    Some((AddressingMode::Implied, Mnemonic::PHP)),
    Some((AddressingMode::Immediate, Mnemonic::ORA)),
    Some((AddressingMode::Accumulator, Mnemonic::ASL)),
    None,
    None,
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::ORA)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::ASL)),
    None,
    Some((AddressingMode::Relative, Mnemonic::BPL)),
    Some((AddressingMode::Indirect(IndexReg::Y), Mnemonic::ORA)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::ORA)),
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::ASL)),
    None,
    Some((AddressingMode::Implied, Mnemonic::CLC)),
    Some((AddressingMode::Absolute(IndexReg::Y), Mnemonic::ORA)),
    None,
    None,
    None,
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::ORA)),
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::ASL)),
    None,
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::JSR)),
    Some((AddressingMode::Indirect(IndexReg::X), Mnemonic::AND)),
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::BIT)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::AND)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::ROL)),
    None,
    Some((AddressingMode::Implied, Mnemonic::PLP)),
    Some((AddressingMode::Immediate, Mnemonic::AND)),
    Some((AddressingMode::Accumulator, Mnemonic::ROL)),
    None,
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::BIT)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::AND)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::ROL)),
    None,
    Some((AddressingMode::Relative, Mnemonic::BMI)),
    Some((AddressingMode::Indirect(IndexReg::Y), Mnemonic::AND)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::AND)),
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::ROL)),
    None,
    Some((AddressingMode::Implied, Mnemonic::SEC)),
    Some((AddressingMode::Absolute(IndexReg::Y), Mnemonic::AND)),
    None,
    None,
    None,
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::AND)),
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::ROL)),
    None,
    Some((AddressingMode::Implied, Mnemonic::RTI)),
    Some((AddressingMode::Indirect(IndexReg::X), Mnemonic::EOR)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::EOR)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::LSR)),
    None,
    Some((AddressingMode::Implied, Mnemonic::PHA)),
    Some((AddressingMode::Immediate, Mnemonic::EOR)),
    Some((AddressingMode::Accumulator, Mnemonic::LSR)),
    None,
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::JMP)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::EOR)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::LSR)),
    None,
    Some((AddressingMode::Relative, Mnemonic::BVC)),
    Some((AddressingMode::Indirect(IndexReg::Y), Mnemonic::EOR)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::EOR)),
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::LSR)),
    None,
    Some((AddressingMode::Implied, Mnemonic::CLI)),
    Some((AddressingMode::Absolute(IndexReg::Y), Mnemonic::EOR)),
    None,
    None,
    None,
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::EOR)),
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::LSR)),
    None,
    Some((AddressingMode::Implied, Mnemonic::RTS)),
    Some((AddressingMode::Indirect(IndexReg::X), Mnemonic::ADC)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::ADC)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::ROR)),
    None,
    Some((AddressingMode::Implied, Mnemonic::PLA)),
    Some((AddressingMode::Immediate, Mnemonic::ADC)),
    Some((AddressingMode::Accumulator, Mnemonic::ROR)),
    None,
    Some((AddressingMode::Indirect(IndexReg::None), Mnemonic::JMP)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::ADC)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::ROR)),
    None,
    Some((AddressingMode::Relative, Mnemonic::BVS)),
    Some((AddressingMode::Indirect(IndexReg::Y), Mnemonic::ADC)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::ADC)),
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::ROR)),
    None,
    Some((AddressingMode::Implied, Mnemonic::SEI)),
    Some((AddressingMode::Absolute(IndexReg::Y), Mnemonic::ADC)),
    None,
    None,
    None,
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::ADC)),
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::ROR)),
    None,
    None,
    Some((AddressingMode::Indirect(IndexReg::X), Mnemonic::STA)),
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::STY)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::STA)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::STX)),
    None,
    Some((AddressingMode::Implied, Mnemonic::DEY)),
    None,
    Some((AddressingMode::Implied, Mnemonic::TXA)),
    None,
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::STY)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::STA)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::STX)),
    None,
    Some((AddressingMode::Relative, Mnemonic::BCC)),
    Some((AddressingMode::Indirect(IndexReg::Y), Mnemonic::STA)),
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::STY)),
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::STA)),
    Some((AddressingMode::ZeroPage(IndexReg::Y), Mnemonic::STX)),
    None,
    Some((AddressingMode::Implied, Mnemonic::TYA)),
    Some((AddressingMode::Absolute(IndexReg::Y), Mnemonic::STA)),
    Some((AddressingMode::Implied, Mnemonic::TXS)),
    None,
    None,
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::STA)),
    None,
    None,
    Some((AddressingMode::Immediate, Mnemonic::LDY)),
    Some((AddressingMode::Indirect(IndexReg::X), Mnemonic::LDA)),
    Some((AddressingMode::Immediate, Mnemonic::LDX)),
    None,
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::LDY)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::LDA)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::LDX)),
    None,
    Some((AddressingMode::Implied, Mnemonic::TAY)),
    Some((AddressingMode::Immediate, Mnemonic::LDA)),
    Some((AddressingMode::Implied, Mnemonic::TAX)),
    None,
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::LDY)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::LDA)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::LDX)),
    None,
    Some((AddressingMode::Relative, Mnemonic::BCS)),
    Some((AddressingMode::Indirect(IndexReg::Y), Mnemonic::LDA)),
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::LDY)),
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::LDA)),
    Some((AddressingMode::ZeroPage(IndexReg::Y), Mnemonic::LDX)),
    None,
    Some((AddressingMode::Implied, Mnemonic::CLV)),
    Some((AddressingMode::Absolute(IndexReg::Y), Mnemonic::LDA)),
    Some((AddressingMode::Implied, Mnemonic::TSX)),
    None,
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::LDY)),
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::LDA)),
    Some((AddressingMode::Absolute(IndexReg::Y), Mnemonic::LDX)),
    None,
    Some((AddressingMode::Immediate, Mnemonic::CPY)),
    Some((AddressingMode::Indirect(IndexReg::X), Mnemonic::CMP)),
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::CPY)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::CMP)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::DEC)),
    None,
    Some((AddressingMode::Implied, Mnemonic::INY)),
    Some((AddressingMode::Immediate, Mnemonic::CMP)),
    Some((AddressingMode::Implied, Mnemonic::DEX)),
    None,
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::CPY)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::CMP)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::DEC)),
    None,
    Some((AddressingMode::Relative, Mnemonic::BNE)),
    Some((AddressingMode::Indirect(IndexReg::Y), Mnemonic::CMP)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::CMP)),
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::DEC)),
    None,
    Some((AddressingMode::Implied, Mnemonic::CLD)),
    Some((AddressingMode::Absolute(IndexReg::Y), Mnemonic::CMP)),
    None,
    None,
    None,
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::CMP)),
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::DEC)),
    None,
    Some((AddressingMode::Immediate, Mnemonic::CPX)),
    Some((AddressingMode::Indirect(IndexReg::X), Mnemonic::SBC)),
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::CPX)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::SBC)),
    Some((AddressingMode::ZeroPage(IndexReg::None), Mnemonic::INC)),
    None,
    Some((AddressingMode::Implied, Mnemonic::INX)),
    Some((AddressingMode::Immediate, Mnemonic::SBC)),
    Some((AddressingMode::Implied, Mnemonic::NOP)),
    None,
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::CPX)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::SBC)),
    Some((AddressingMode::Absolute(IndexReg::None), Mnemonic::INC)),
    None,
    Some((AddressingMode::Relative, Mnemonic::BEQ)),
    Some((AddressingMode::Indirect(IndexReg::Y), Mnemonic::SBC)),
    None,
    None,
    None,
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::SBC)),
    Some((AddressingMode::ZeroPage(IndexReg::X), Mnemonic::INC)),
    None,
    Some((AddressingMode::Implied, Mnemonic::SED)),
    Some((AddressingMode::Absolute(IndexReg::Y), Mnemonic::SBC)),
    None,
    None,
    None,
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::SBC)),
    Some((AddressingMode::Absolute(IndexReg::X), Mnemonic::INC)),
    None,
];
